### ISSUE TITLE
The link in the Cargo.toml is wrong

### ISSUE THREAD

**Issue by Decodetalkers** [yuja/tree-sitter-qmljs#1]
The link in Cargo.toml is wrong, you write https://github.com/tree-sitter/tree-sitter-qmljs
and 
```rust
include_str!("../../queries/highlights-typescript.scm"),
```
what does this line mean?

**Comment by Decodetalkers** [comment]
And seems that you have realize the highlight of neovim , why not make a pr to nvim-treesitter?

**Comment by Decodetalkers** [comment]
> The link in Cargo.toml is wrong and
> 
> ```rust
> include_str!("../../queries/highlights-typescript.scm"),
> ```
> 
> what does this line mean?

I see ,you have write a makefile..

**Comment by yuja** [comment]
> I see ,you have write a makefile..

Yep. Maybe it's better to add these symlinks to the repository.

> And seems that you have realize the highlight of neovim , why not make a pr to nvim-treesitter?

I don't know neovim. would be nice if you (or neovim user) make a pr. thanks.

**Comment by Decodetalkers** [comment]
emmmm...

I mean
the repository in Cargo.toml, I think it should from
```toml
repository = "https://github.com/tree-sitter/tree-sitter-qmljs"
```
to 
```toml 
repository = "https://github.com/yuja/tree-sitter-qmljs"
```

**Comment by yuja** [comment]
> repository =

Auto-generated code was wrong. Fixed, thanks.

**Comment by Decodetalkers** [comment]
> > repository =
> 
> Auto-generated code was wrong. Fixed, thanks.

and I think you should better publish a new version of package to crate?

**Comment by yuja** [comment]
> and I think you should better publish a new version of package to crate?

will do in a day if there are no other problems.

**Comment by clason** [comment]
@yuja This prevents the parser from being correctly installed from archive on Windows (which doesn't support symlinks outside admin/dev mode). Is this strictly necessary? Submodules would be an alternative if you need it.
