### ISSUE TITLE
Remove symlinks from repo

### ISSUE THREAD

**Issue by clason** [yuja/tree-sitter-qmljs#12]
The presence of symlinks prevents this parser from being installed on Windows (were symlinks are not supported outside admin/dev mode).

Can you replace the symlinked queries with just a copy? Submodules would also be an alternative.

**Comment by yuja** [comment]
iirc, It's a workaround for cargo, and I thought it would work so long as I publish the source to crates.io.

Copy also works. I think it's also good to remove `HIGHLIGHTS_QUERY` from the Rust binding assuming downstream users will probably have its own query definitions.

**Comment by clason** [comment]
If you install via cargo, yes, but Rust is not the only consumer ;)

(Sorry, I should have added more context: This is for nvim-treesitter, which downloads the parser as an archive (release archive, ideally), extracts it, and then builds it manually.)

**Comment by yuja** [comment]
Ah, okay, and their packaging system is strict enough to reject invalid symlinks even if unused? Makes sense.

Let's remove query files from Rust binding, then. I think that's the easiest option and seems good.

**Comment by clason** [comment]
> packaging system is strict enough to reject invalid symlinks even if unused?

No, it's really just Windows that refuses to create a symlink when extracting a tar archive. (Unless you are root.)

**Comment by clason** [comment]
You might also wish to regenerate the parser and bindings with the latest tree-sitter CLI (0.22.6); a lot of progress was made in the last year ;)

**Comment by yuja** [comment]
> No, it's really just Windows that refuses to create a symlink when extracting a tar archive. (Unless you are root.)

Oh, `git` usually ignores symlinks (or create dummy files) on Windows, but a certain subcommand might not.

> regenerate the parser and bindings with the latest tree-sitter CLI (0.22.6)

Already done (not tagged a release though.)

**Comment by clason** [comment]
> Oh, git usually ignores symlinks

Yes, `git` works, but there are reasons why we can't use that (any longer). And since only six out of ~300 parsers use symlinks, I thought it'd be simplest (and safest) to ask them to do without ;)

Thank you for the quick change, it is really appreciated!
