### ISSUE TITLE
Can't get syntax highlighting enabled

### ISSUE THREAD

**Issue by fwsmit** [yuja/tree-sitter-qmljs#4]
I tried to use this via nvim-treesitter. I installed the module via `:TSInstall qmljs`. The problem is that I don't see any syntax highlighting. I also tried `:TSBufEnable highlight`, but that didn't do anything either. Setting the file type to qml manually (since it's not recognized out of the box) didn't work either.

So how do I make sure syntax highlighting is enabled for qml files in neovim?

**Comment by yuja** [comment]
I don't know the neovim details. @Decodetalkers do you have any idea?

If that is a general question about neovim integration, maybe you can get more help at
https://github.com/nvim-treesitter/nvim-treesitter

**Comment by Decodetalkers** [comment]
> I tried to use this via nvim-treesitter. I installed the module via `:TSInstall qmljs`. The problem is that I don't see any syntax highlighting. I also tried `:TSBufEnable highlight`, but that didn't do anything either. Setting the file type to qml manually (since it's not recognized out of the box) didn't work either.
> 
> So how do I make sure syntax highlighting is enabled for qml files in neovim?

Set ft to qmljs ,pls

**Comment by fwsmit** [comment]
Thanks, that worked!

**Comment by polirritmico** [comment]
The nvim documentation to automatically setting the filetype is under `:h ftdetect`

```vim
" ~/.config/nvim/ftdetect/qml.vim
au BufRead,BufNewFile *.qml		setfiletype qmljs
```
